Reloadable Tooltips
friendlyhj/ZenRecipeReloading pull request #17
Opened 2024-09-20 19:28 UTC by kurrycat2004

(cherry picked from commit 82d457bef894692154ab1cceac94e17ce7dbb8c8)

Im not sure if this is within the scope of the mod, or even if this is all working correctly (from what i tested it seemed to all work), but i might as well make a PR

Also i did not manage to get it to run using the base build script (i didnt really try after seeing it not work immediately) so i switched to the GTCEu build script in my fork. I can PR that too, but this PR only contains the reloadable tooltips.

2024-09-21 05:13 UTC, friendlyhj requested changes

2024-09-21 05:13 UTC, friendlyhj commented on src/main/java/youyihj/zenrecipereloading/mixins/crafttweaker/IngredientMapEntryMixin.java
> +        if (!(obj instanceof IngredientMap.IngredientMapEntry<?> other)) return false;
Don't use java 8+ syntax

2024-09-21 05:13 UTC, friendlyhj commented on src/main/java/youyihj/zenrecipereloading/mixins/crafttweaker/IngredientMapEntryMixin.java
> +               this.entry.equals(((IngredientMapEntryMixin<?>)(Object)other).entry);
Are you sure we can use mixin class directly?

2024-09-21 09:58 UTC, kurrycat2004 commented on src/main/java/youyihj/zenrecipereloading/mixins/crafttweaker/IngredientMapEntryMixin.java
> +               this.entry.equals(((IngredientMapEntryMixin<?>)(Object)other).entry);
It worked, but i also wasnt happy with it. I didnt get it to work using an Accessor. I could probably do it with an interface instead

2024-09-22 13:13 UTC, friendlyhj approved these changes

2024-09-22 13:16 UTC, merged